SpiceProject/Controllers/CartController.cs
using Food.DataLayer;
using SpiceProject.Models;
using SpiceProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Food.DomainLayer;
using Microsoft.AspNet.Identity;

namespace SpiceProject.Controllers
{
    public class CartController : Controller
    {
       
        // GET: Cart
        ApplicationDbContext db = new ApplicationDbContext();

        SpiceDbContext context = new SpiceDbContext();
        OrderHeader or = new OrderHeader();
        public OrderDetailsCart detailCart { get; set; }
        

        public ActionResult Summary()
        {
            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Food.DomainLayer.OrderHeader()
            };

            OrderHeader or = new OrderHeader();
            detailCart.OrderHeader.OrderTotal = 0;

            var claimsidentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsidentity.FindFirst(ClaimTypes.Name);
            ViewBag.userId = User.Identity.GetUserId();
            string userId = ViewBag.userId;


            ApplicationUser applicationUser = db.Users.Where(c => c.Id == userId).FirstOrDefault();

            var cart = context.ShoppingCart.Where(c => c.AppUserId == userId);
            if (cart != null)
            {
                detailCart.ListCart = cart.ToList();
            }

            foreach (var list in detailCart.ListCart)
            {
                list.MenuItem = context.MenuItem.FirstOrDefault(m => m.Id == list.MenuItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);
            }

            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;
            detailCart.OrderHeader.PickupName = applicationUser.UserName;
            detailCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
            detailCart.OrderHeader.PickUpTime = DateTime.Now;
            

           
            return View(detailCart);
        }



        [HttpPost]
        
         public ActionResult Summary(OrderDetailsCart detailsCart)
        {
            var claimsidentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsidentity.FindFirst(ClaimTypes.Name);
            ViewBag.userId = User.Identity.GetUserId();
            string userId = ViewBag.userId;


            ApplicationUser applicationUser = db.Users.Where(c => c.Id == userId).FirstOrDefault();

            var cart = context.ShoppingCart.Where(c => c.AppUserId == userId).FirstOrDefault();


            var menu = context.MenuItem.FirstOrDefault(m => m.Id == cart.MenuItemId);


            //or.OrderTotal = detailCart.OrderHeader.OrderTotal + (menu.Price* cart.Count);
            

            or.UserId = detailsCart.OrderHeader.UserId;
            or.OrderDate = DateTime.Now;
           
            or.OrderTotalOriginal = detailsCart.OrderHeader.OrderTotalOriginal;
           
            or.PickUpTime = DateTime.Now;
            or.PickUpDate = DateTime.Now;
            or.PickupName = detailsCart.OrderHeader.PickupName;
            or.PhoneNumber = detailsCart.OrderHeader.PhoneNumber;
            or.Comments = detailsCart.OrderHeader.Comments;

            context.OrderHeader.Add(or);
            context.SaveChanges();


            return RedirectToAction("Transaction");
            
        }

        public ActionResult Transaction()
        {
            return View();
        }
        public ActionResult OrderPlaced()
        {
            return View();
        }





       



    }
}

SpiceProject/Controllers/OrderController.cs
using Food.DataLayer;
using Food.DomainLayer;
using Microsoft.AspNet.Identity;
using SpiceProject.Models;
using SpiceProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace SpiceProject.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order


        private readonly ApplicationDbContext _db;

        SpiceDbContext context = new SpiceDbContext();
        OrderHeader v = new Food.DomainLayer.OrderHeader();

        public OrderController(ApplicationDbContext db)
        {
            _db = db;
           
        }

        [Authorize]
        public ActionResult Confirm(int id)
        {
            var claimsidentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsidentity.FindFirst(ClaimTypes.NameIdentifier);
          

            OrderDetailsViewModel orderDetailsViewModel = new OrderDetailsViewModel()
            {
            
            OrderHeader = context.OrderHeader.FirstOrDefault(o => o.Id == id && o.UserId == claim.Value),
               
            OrderDetails = context.OrderDetails.Where(o => o.OrderId == id).ToList()
            };

            return View("Summary");


        }




    

            public ActionResult PlaceOrder(int id)
            {
           
                return View("PlaceOrder");

        }


           
            

























           
        
    }
}

SpiceProject/Views/Cart/Index.cshtml
IEnumerable<Food.DomainLayer.MenuItem>

    @{
        ViewBag.Title = "Index";
    }

    <h2>Index</h2>
    

                <table class="table">
                    <tr>
                        <th>Menu Id</th>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <th>Menu Name</th>
                        <td>@Model.Name</td>
                    </tr>


                    <tr>
                        <th>Spiciness Name</th>
                        <td>@Model.Spicyness</td>

                    </tr>

                    <tr>
                        <th>Price</th>
                        <td>@Model.Price</td>

                    </tr>

                    @{int sum = 0;


                        sum = Convert.ToInt32(Model.Price) + sum;

                    }
                    <tr>
                        <th>Total Price</th>
                        <td>@sum</td>

                    </tr>



                </table>

SpiceProject/Views/Cart/Myorder.cshtml
@*@model IEnumerable<Food.DomainLayer.MenuItem>*@
@{
    ViewBag.Title = "Myorder";
}


<h2>Myorder</h2>

@{
    int sum = 0;
}

<link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" > </script>  
 <div id = "dvContents"> 
     <table class="table table-hover" width="100%">
         <thead>
            
             <tr> 
                 <th> Menu NO </th>  
                 <th> Menu Name </th> 
                 <th> Image </th>  
                 <th> Price </th>  
                 <th> Remove </th> 
             </tr>  
         </thead> 
         </table>
     </div>

@foreach (var item in (List<Food.DomainLayer.MenuItem>)Session["cart"])
{
    @item.Id
}

SpiceProject/Views/Cart/OrderPlaced.cshtml
@{
    ViewBag.Title = "OrderPlaced";
}

<h2 style="text-align:center;width:50px;height:50px;color:darkorange">Order Placed</h2>
<h1>Enjoy Your Meal</h1>
<a href="/Spice/Index" class="btn btn-dark" style="color:chocolate">Continue Ordering</a>

<div class="col-lg-3">
    <img id="loading" src="~/Images/Yum.gif" alt="Updating ..." />
</div>

SpiceProject/Views/Cart/Summary.cshtml
@model SpiceProject.ViewModels.OrderDetailsCart
@{
    ViewBag.Title = "Summary";
}

<h2>Summary</h2>

@using (Html.BeginForm("Summary", "Cart"))
{
    if (Model.ListCart.Count > 0)
    {
        <br />
        <input id="userId" asp-for="@Model.ListCart[0].AppUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Order Summary
                        </div>

                        <div class="col-6 text-right">
                            <a href="/Spice/GetShoppingCart" class="btn btn-default">Back To Cart</a>

                        </div>
                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class=" row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">PickUp Details:</span>
                                        </h4>
                                    </div>

                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-9" style="color:black">
                                            @Html.TextBoxFor(e => e.OrderHeader.PickupName)

                                        </div>
                                    </div>

                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Number</label>
                                        </div>
                                        <div class="col-9" style="color:black">
                                            @Html.TextBoxFor(e => e.OrderHeader.PhoneNumber)


                                        </div>
                                    </div>

                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Pickup Date</label>
                                        </div>
                                        <div class="col-9" style="color:black">

                                            <input type="date" id="datepicker" />

                                        </div>
                                    </div>

                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>PickUp Time</label>
                                        </div>
                                        <div class="col-9" style="color:black">
                                            @Html.TextBoxFor(e => e.OrderHeader.PickUpTime)

                                        </div>
                                    </div>

                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Instuctions</label>
                                        </div>
                                        <div class="col-9" style="color:black">
                                            @Html.TextAreaFor(e => e.OrderHeader.Comments)
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-5 offset-lg-1">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Order Summary:</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        <!--this shows how to create and use variables here-->
                                        @{ var total = 0.0;}

                                        @foreach (var details in Model.ListCart)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div>
                                                    <h6 class="my-0">@details.MenuItem.Name</h6>
                                                    <small class="text-muted">Quantity: @details.Count</small>
                                                </div>

                                                <span class="text-muted">$@(details.MenuItem.Price * details.Count)</span>
                                                @{ total += (details.MenuItem.Price * details.Count); }
                                            </li>
                                                    }
                                        @if (Model.OrderHeader.CouponCode != null)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div class="text-success">
                                                    <h6 class="my-0">Promo Code</h6>
                                                    <small class="text-success">@Model.OrderHeader.CouponCode</small>
                                                </div>

                                                <span class="text-success">-$@(total - Model.OrderHeader.OrderTotal)</span>
                                            </li>
                                        }

                                        <li class="list-group-item d-flex justify-content-between">
                                            <small class="text-info">Total (USD)</small>
                                            <strong class="text-info">$@(Model.OrderHeader.OrderTotal)</strong>
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-4 offset-8">
                                @{
                                    var OrderTotalForStrip = Model.OrderHeader.OrderTotal * 100;
                                }

                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="/Cart/Transaction" class="btn btn-default" id="plc_btn">Pay Now</a>
                                @*@Html.ActionLink("Place Order", "PalceOrder", "Order")*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


                                    }
                                    else
                                    {
        <div class="backgroundWhiteBorder">No items added to the shopping cart...</div>
                                    }
 }







@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script>

    $("#plc_btn").click(function) {

        alert('Order Placed..Enjoy Your Food');




    });

</script>

SpiceProject/Views/Cart/Transaction.cshtml
@{
    ViewBag.Title = "Transaction";
}

<h2 style="text-align:center">Pay Now</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Payment Details
                    </h3>
                    <div class="checkbox pull-right">
                        <label>
                            <input type="checkbox" />
                            Remember
                        </label>
                    </div>
                </div>
                <div class="panel-body">
                    <form role="form">
                        <div class="form-group">
                            <label for="cardNumber">
                                CARD NUMBER
                            </label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="cardNumber" placeholder="Valid Card Number"
                                       required autofocus />
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-7 col-md-7">
                                <div class="form-group">
                                    <label for="expityMonth">
                                        EXPIRY DATE
                                    </label>
                                    <div class="col-xs-6 col-lg-6 pl-ziro">
                                        <input type="text" class="form-control" id="expityMonth" placeholder="MM" required />
                                    </div>
                                    <div class="col-xs-6 col-lg-6 pl-ziro">
                                        <input type="text" class="form-control" id="expityYear" placeholder="YY" required />
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-5 col-md-5 pull-right">
                                <div class="form-group">
                                    <label for="cvCode">
                                        CV CODE
                                    </label>
                                    <input type="password" class="form-control" id="cvCode" placeholder="CV" required />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <ul class="nav nav-pills nav-stacked">
                <li class="active">
                    <a href="#"><span class="badge pull-right"><span class="glyphicon glyphicon-usd"></span></span> Final Payment</a>
                </li>
            </ul>
            <br />
            <a href="/Cart/OrderPlaced" class="btn btn-success btn-lg btn-block" role="button">Pay</a>
        </div>
    </div>
</div>
<style>
    body {
        margin-top: 20px;
    }

    .panel-title {
        display: inline;
        font-weight: bold;
    }

    .checkbox.pull-right {
        margin: 0;
    }

    .pl-ziro {
        padding-left: 0px;
    }
</style>